version: '3.8'
services:

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./frontend/dist:/frontend
      - ./backend:/backend/
    ports:
      - "8080:80"
      - "8181:81"
    networks:
      - internal
    links:
      - backend
    environment:
      - NGINX_PORT=80
      - NGINX_HOST=frontend

  backend:
    image: php:8.2-fpm-alpine
    volumes:
      - ./backend:/backend/
    build: ./backend
    depends_on:
      - general-db
    networks:
      - internal
      - general-db-network

  general-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: forge
      POSTGRES_DB: forge
    networks:
      - general-db-network

networks:
  internal:
    driver: bridge
  general-db-network:
    driver: bridge